### ISSUE TITLE
Expose all diagnostic together for better namespacing

### ISSUE THREAD

**Issue by zsofitoth** [Siteimprove/alfa#1107]
Re-export all diagnostics namespaces in a clean group (e.g `Rule.Diagnostic.isColorError`). Make sure all diagnostics have `isThisTypeOfDiagnostic` method.

**Comment by Jym77** [comment]
Ideally, it would be possible to merge namespaces, so that each rule with an extended diagnostic could declare
```
export namespace Diagnostic {
  export class Foo extends act.Diagnostic // needs to be the class so name conflict need to be handled
  …

  export namespace Foo {
    …
    export function isFoo
  }

  export const { isFoo } = Foo
}
```
and that would merge within the same `Diagnostic` namespace so that `Diagnostic.isFoo` exists.

Not fully sure how namespace merging happens, may need some trick and tweak 😕 

Otherwise, we let the individual rule export `Foo` with `isFoo` in the namespace, and add a `alfa-rules/src/common/act/diagnostic.ts` file with a `Diagnostic` namespace that only re-export the `isFoo` functions (and is re-exported by the module).

---
Also, when writing the `isFoo` for subclasses, must overload the signature depending whether `value` is already a `Diagnostic` or not, otherwise the type narrowing breaks for the `Diagnostic` but not `Foo` object (the result is `false` but the narrow `value is Foo` then goes to `never`).
