### ISSUE TITLE
Investigate considering more characters as non-text content

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#1220]
Many Unicode characters are actually non-text content but symbols (e.g., arrows, …) and could be considered as non-text content, notably for the purpose of R14.

We should find a suitable class of Unicode characters to ignore.

**Comment by dan-tripp-siteimprove** [comment]
I propose that we expand this "suitable class of Unicode characters to ignore" to include characters such as "+".

I say this because "+" is:
* Outside of [WCAG's definition of 'text'](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html#dfn-text) - which is referenced by the SC. 
* Outside of [alfa's definition of "textual content"](https://alfa.siteimprove.com/terms/textual-content) - which is referenced by the alfa docs for this rule.
* Inside of [ACT's defintion of 'non-text content'](https://www.w3.org/TR/WCAG21/#dfn-non-text-content) - which is referenced by the corresponding ACT rule for this alfa rule.

Adding something like `.replace(/\p{S}/gu, "")` to removePunctuationAndNormalise in src/sia-r14/rule.ts might do the job.

**Comment by Jym77** [comment]
Agreed, Symbol class is probably good to consider as non-text.
Probably also Control.

Letter, Number, Mark, and Separator are likely the classes we want to keep.

**Comment by Jym77** [comment]
@dan-tripp-siteimprove Do you feel like making a PR for it?

**Comment by Jym77** [comment]
Also note that we could use a similar heuristic in [the Applicability of R66/R69](https://github.com/Siteimprove/alfa/blob/main/packages/alfa-rules/src/common/applicability/non-disabled-texts.ts#L78-L85) to eliminate text nodes that do not convey anything in a human language (if it's only Punctuation, Symbol and Control, do not care).

**Comment by dan-tripp-siteimprove** [comment]
> @dan-tripp-siteimprove Do you feel like making a PR for it?

Sure thing - I made a PR here: https://github.com/Siteimprove/alfa/pull/1316

**Comment by dan-tripp-siteimprove** [comment]
> Also note that we could use a similar heuristic in [the Applicability of R66/R69](https://github.com/Siteimprove/alfa/blob/main/packages/alfa-rules/src/common/applicability/non-disabled-texts.ts#L78-L85) to eliminate text nodes that do not convey anything in a human language (if it's only Punctuation, Symbol and Control, do not care).

Maybe another day.
