### ISSUE TITLE
SIA-R62: false negative caused by surrounding text that is far away

### ISSUE THREAD

**Issue by dan-tripp-siteimprove** [Siteimprove/alfa#1296]
Consider this HTML: 

```
<p>
	<b>.</b> <br>
	surrounding text <br>
	surrounding text <br>
	surrounding text <br>
	<a href="#" style="text-decoration: none">link text</a><br>
	surrounding text <br>
	surrounding text <br>
	surrounding text <br>
</p>
```

Actual behaviour: this passes SIA-R62.

Expected behaviour: that this would fail SIA-R62. 

Alfa seems to be considering the `<b>.</b>` to be "surrounding text".  I thought that "surrounding text" needs to mean "immediately adjacent" in order for it to be useful for the user to distinguish the link.  So either I'm wrong, or alfa is. 

I can add many more lines of `surrounding text <br>` to make the `<b>.</b>` very far away from the `<a>` tag - and alfa seems to still consider the `<b>.</b>` to be surrounding text.

**Comment by Jym77** [comment]
Yes, any (significant) difference with some text within the same paragraph is enough for R62 to pass. This is clearly not enough for 1.4.1, but R62 is more lenient (as always).
The problem is that there is no sure way to decide whether there is enough different text close enough to satisfy 1.4.1. As always, passing the rule does not mean that 1.4.1 is satisfied, only that Alfa could not find a sure enough problem that it should be flagged. Manual tests are always needed to correctly audit a page.
This is very similar conceptually to R69 (color contrast) only failing when the highest possible contrast is too low.

**Comment by dan-tripp-siteimprove** [comment]
Thank you for the explanation.
