### ISSUE TITLE
r111 documentation page is missing

### ISSUE THREAD

**Issue by tgrushka** [Siteimprove/alfa#1570]
The expected documentation for this R111 Target Size rule at:

https://alfa.siteimprove.com/rules/sia-r111

currently returns a 404 error.

Can't seem to find where these doc pages are generated in the code (if they are).

Thanks for the great test suite!

**Comment by Jym77** [comment]
Hi @tgrushka, thanks for using Alfa.

Indeed, we haven't written that documentation yet…
The reason is that [the corresponding ACT rule](https://github.com/act-rules/act-rules.github.io/pull/1919) is still in early development and I expect it to change, plus I also expect R111 to change after seeing how it actually runs (I know there are several corner cases it doesn't handle, and want to gather data on what is actually used on the web before over-engineering it).

So, I expect the rule to change significantly in the short term and did not want to write too much documentation that will soon get outdated.

---
In its current state, the rule simply looks at the bounding box of focusable widgets and checks that it is at least `44×44px`.
This clearly leaves some false negative (accepting too much) in case of rounded corners or rotated content (these are acceptable).
This doesn't handle some of the WCAG exception around "User Agent size" (we can probably do something around it) or "essential size" (this, we probably won't be able to manage within Alfa).

---
These pages are generated from another repository that is private. I'm not 100% sure why it was set up like that, but haven't reverted that decision yet.

**Comment by Jym77** [comment]
Hi @tgrushka , we've written and published the documentation for [R111](https://alfa.siteimprove.com/rules/sia-r111) (and [R113](https://alfa.siteimprove.com/rules/sia-r113), for 2.5.8). Closing this.

@jrpool, FYI.
