### ISSUE TITLE
Figure out workflow for dealing with change log entries

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#749]
As part of #221, we agreed to start doing change logs as part of pull requests so it didn't become an afterthought. However, it has now happened more than once that a PR has been opened with a new change log entry under `[Unreleased]`, a new version has been published, the PR has been merged, and now suddenly the change log entry appears under the latest release rather than `[Unreleased]`. The most recent example is b666e12bce1fadd7d70969f0e9ee7426528d6d9c.

We therefore need a better way of handling change logs and I'm hoping that https://github.com/yarnpkg/berry/pull/2358 might be the answer.

**Comment by Jym77** [comment]
Might be handled together or not…

Currently, we can't really deeplink to specific sub-sub-headers in changelog because the are numbered from top to bottom.
That is, https://github.com/Siteimprove/alfa/blob/main/CHANGELOG.md#fixed-9 is not going to point to the same "Fixed" subsubheading as time goes. I've been using that link for "look issue has been fixed in a previous release", but that is actually a bad idea since it now points to something else 😕 

Might be cool if we can create stable deeplink (e.g. `#fixed-[version]`) for this purpose.

**Comment by Jym77** [comment]
Closed by #1390 and #1462.
