### ISSUE TITLE
Accessible name computation doesn't handle labels and duplicate IDs

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#780]
```html
<form>
  <label>
    Hello world
    <input id="input" />
  </label>

  <label>
    Lorem Ipsum
    <input id="input" />
  </label>
</form>
```
The first `<input>` gets its name computed correctly. The second gets no name.
Changing the `id` of the second `<input>` let it gets its name correctly.
Both Chrome and Firefox give a name to the second `<input>`, despite its duplicate `id`.

I haven't dug into the computation to figure out what exactly goes wrong 🤷

**Comment by kasperisager** [comment]
This happens due to the following check in `nameFromLabel()`:

https://github.com/Siteimprove/alfa/blob/0b50a08e74aa1edf96f097a40462eba32daed742/packages/alfa-aria/src/feature.ts#L149-L167

The intent of this check is to ensure that `<label>` elements with `for` attributes are only assigned to the _first_ element with the corresponding ID, but this interferes with implicit `<label>` references.
